image: node:18.17-bullseye

stages:
  - checks
  - build
  - deploy

lint-check:
  stage: checks
  before_script:
    - yarn install --immutable
  script:
    - yarn run lint:check
  only:
    - main
    - merge_requests

audit-check:
  stage: checks
  allow_failure: true
  script:
    - yarn npm audit --severity high
  only:
    - main
    - merge_requests

build:
  stage: build
  before_script:
    - yarn install --immutable
  script:
    - yarn run build
  only:
    - merge_requests

deploy-prod:
  stage: deploy
  script:
    - curl -X POST "$CLOUDFLARE_DEPLOY_HOOK"
  only:
    - main
