name: Deploy page to Cloudflare

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --immutable
      - name: Build
        run: yarn run build
        env:
          VITE_SENTRY_ENABLED: ${{ variables.VITE_SENTRY_ENABLED }}
          VITE_SENTRY_DSN: ${{ secrets.VITE_SENTRY_DSN }}
          VITE_SENTRY_ENVIRONMENT: ${{ secrets.VITE_SENTRY_ENVIRONMENT }}
          SENTRY_PLUGIN_ENABLED: ${{ variables.SENTRY_PLUGIN_ENABLED }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_GOOGLE_MEASUREMENT_ID: ${{ secrets.VITE_GOOGLE_MEASUREMENT_ID }}
      - name: Save untracked files
        uses: actions/upload-artifact@v4
        with:
          name: untracked-files
          path: './dist'
  publish:
    runs-on: ubuntu-latest
    needs: build
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: untracked-files
          path: './dist'
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'galleryeet'
          directory: './dist'
          wranglerVersion: '3'